# Generated by Django 4.2.9 on 2024-03-10 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_accadmin_adcadmin_enterprisecourier_volunteercourier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EMAAdmin",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("ema_name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=("users.user",),
        ),
    ]
