# Generated by Django 4.2.9 on 2024-03-10 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_emaadmin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accadmin",
            options={"verbose_name": "ACC Admin"},
        ),
        migrations.AlterModelOptions(
            name="adcadmin",
            options={"verbose_name": "ADC Admin"},
        ),
        migrations.AlterModelOptions(
            name="emaadmin",
            options={"verbose_name": "EMA Admin"},
        ),
        migrations.AlterModelOptions(
            name="enterprisecourier",
            options={"verbose_name": "Enterprise Courier"},
        ),
        migrations.AlterModelOptions(
            name="volunteercourier",
            options={"verbose_name": "Volunteer Courier"},
        ),
    ]
