# Generated by Django 4.2.9 on 2024-04-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("aid", "0005_alter_accaid_options_alter_adcaid_options"),
        ("users", "0004_alter_accadmin_options_alter_adcadmin_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accadmin",
            name="acc_name",
        ),
        migrations.RemoveField(
            model_name="adcadmin",
            name="adc_name",
        ),
        migrations.RemoveField(
            model_name="volunteercourier",
            name="availability",
        ),
        migrations.AddField(
            model_name="accadmin",
            name="center",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins",
                to="aid.acc",
                verbose_name="Collection Center",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adcadmin",
            name="center",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins",
                to="aid.adc",
                verbose_name="Distribution Center",
            ),
            preserve_default=False,
        ),
    ]
