# Generated by Django 4.2.9 on 2024-05-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_accadmin_acc_name_remove_adcadmin_adc_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprisecourier",
            name="city",
            field=models.CharField(default=" ", max_length=100, verbose_name="City"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="volunteercourier",
            name="city",
            field=models.CharField(max_length=100, verbose_name="City"),
        ),
    ]
