# Generated by Django 4.2.9 on 2024-01-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ACC",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
            ],
            options={
                "verbose_name": "Aid Collection Center",
            },
        ),
        migrations.CreateModel(
            name="ADC",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
            ],
            options={
                "verbose_name": "Aid Distribution Center",
            },
        ),
        migrations.CreateModel(
            name="ADCAid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aids",
                        to="aid.adc",
                        verbose_name="Distribution Center",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ACCAid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                ("quantity", models.IntegerField(verbose_name="Quantity")),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aids",
                        to="aid.acc",
                        verbose_name="Collection Center",
                    ),
                ),
            ],
        ),
    ]
