# Generated by Django 4.2.9 on 2024-03-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aid", "0002_adcaid_demanded_stock_adcaid_standard_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="EMA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("location", models.CharField(max_length=100, verbose_name="Location")),
            ],
            options={
                "verbose_name": "Emergency Management Authority",
            },
        ),
    ]
