# Generated by Django 4.2.9 on 2024-03-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("aid", "0003_ema"),
    ]

    operations = [
        migrations.AddField(
            model_name="acc",
            name="ema",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acc_centers",
                to="aid.ema",
                verbose_name="Emergency Management Authority",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adc",
            name="ema",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adc_centers",
                to="aid.ema",
                verbose_name="Emergency Management Authority",
            ),
            preserve_default=False,
        ),
    ]
