# Generated by Django 4.2.9 on 2024-03-10 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("aid", "0004_acc_ema_adc_ema"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accaid",
            options={"verbose_name": "ACC Aid"},
        ),
        migrations.AlterModelOptions(
            name="adcaid",
            options={"verbose_name": "ADC Aid"},
        ),
    ]
