# Generated by Django 4.2.9 on 2024-04-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aid", "0006_aidtype_alter_accaid_type_alter_adcaid_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="accaid",
            name="standard_stock",
            field=models.IntegerField(default="0", verbose_name="Standard Stock"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accaid",
            name="status",
            field=models.CharField(default="", verbose_name="Status"),
            preserve_default=False,
        ),
    ]
