# Generated by Django 4.2.9 on 2024-04-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aid", "0008_remove_accaid_standard_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="accaid",
            name="standard_stock",
            field=models.IntegerField(default=1, verbose_name="Standard Stock"),
            preserve_default=False,
        ),
    ]
