# Generated by Django 4.2.9 on 2024-04-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aid", "0009_accaid_standard_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accaid",
            name="standard_stock",
            field=models.IntegerField(default=0, verbose_name="Standard Stock"),
        ),
    ]
