# Generated by Django 4.2.9 on 2024-04-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aid", "0010_alter_accaid_standard_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="AidTypeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Aid Type Request",
            },
        ),
    ]
