# Generated by Django 4.2.9 on 2024-05-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aid", "0012_aidtype_volume"),
    ]

    operations = [
        migrations.AddField(
            model_name="acc",
            name="city",
            field=models.CharField(default=" ", max_length=100, verbose_name="City"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adc",
            name="city",
            field=models.CharField(default=" ", max_length=100, verbose_name="City"),
            preserve_default=False,
        ),
    ]
