# Generated by Django 4.2.9 on 2024-05-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("aid", "0012_aidtype_volume"),
        ("users", "0005_remove_accadmin_acc_name_remove_adcadmin_adc_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("load", models.CharField(max_length=100, verbose_name="Load")),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aid.acc", verbose_name="Collection Center"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.volunteercourier", verbose_name="Owner"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aid.adc", verbose_name="Distribution Center"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnterpriseTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("load", models.CharField(max_length=100, verbose_name="Load")),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aid.acc", verbose_name="Collection Center"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.enterprisecourier", verbose_name="Owner"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="aid.adc", verbose_name="Distribution Center"
                    ),
                ),
            ],
        ),
    ]
