# Generated by Django 4.2.9 on 2024-05-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprisetask",
            name="load",
        ),
        migrations.RemoveField(
            model_name="volunteertask",
            name="load",
        ),
        migrations.AddField(
            model_name="enterprisetask",
            name="load_quantity",
            field=models.IntegerField(default=0, verbose_name="Load Quantity"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enterprisetask",
            name="load_type",
            field=models.CharField(default="", max_length=100, verbose_name="Load Type"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteertask",
            name="load_quantity",
            field=models.IntegerField(default=0, verbose_name="Load Quantity"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="volunteertask",
            name="load_type",
            field=models.CharField(default=" ", max_length=100, verbose_name="Load Type"),
            preserve_default=False,
        ),
    ]
