# Generated by Django 4.2.9 on 2024-05-01 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0002_remove_enterprisetask_load_remove_volunteertask_load_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprisetask",
            name="load_quantity",
        ),
        migrations.RemoveField(
            model_name="enterprisetask",
            name="load_type",
        ),
        migrations.RemoveField(
            model_name="volunteertask",
            name="load_quantity",
        ),
        migrations.RemoveField(
            model_name="volunteertask",
            name="load_type",
        ),
    ]
