# Generated by Django 4.2.9 on 2024-05-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0005_volunteertask_code_volunteertask_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprisetask",
            name="done",
            field=models.BooleanField(default=False, verbose_name="Task Completed"),
        ),
    ]
